# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: body_classify.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'body_classify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62ody_classify.proto\x12\x08\x62ody_cls\"1\n\x0cImageRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"C\n\rImageResponse\x12\x15\n\rcar_type_body\x18\x01 \x01(\t\x12\x1b\n\x13\x63\x61r_type_body_score\x18\x02 \x01(\x02\x32Y\n\x16ImageProcessingService\x12?\n\x0cProcessImage\x12\x16.body_cls.ImageRequest\x1a\x17.body_cls.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'body_classify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=33
  _globals['_IMAGEREQUEST']._serialized_end=82
  _globals['_IMAGERESPONSE']._serialized_start=84
  _globals['_IMAGERESPONSE']._serialized_end=151
  _globals['_IMAGEPROCESSINGSERVICE']._serialized_start=153
  _globals['_IMAGEPROCESSINGSERVICE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
